network:
  ethernets:
    eth0:
      dhcp4: no                    # 关闭DHCP，手动配置静态IP
      addresses: [192.168.8.36/24] # WSL静态IP（与主机同网段）
      gateway4: 192.168.8.1       # 网关（和主机一致）
      nameservers:
        addresses: [114.114.114.114, 8.8.8.8] # DNS服务器（保证解析正常）
  version: 2
  renderer: networkd               # 强制使用networkd渲染器（WSL 2推荐）